### ISSUE TITLE
Exclude subdecks

### ISSUE THREAD

**Issue by vintotal** [ThoreBor/ChineseWordsFinder#1]
你們好！
 I just installed this addon. It has very powerful sorting abilities! I would like to be able to analyse the notes of a deck without analysing the subdecks notes.
In the browser it would be something like this:
deck:1a.中文語彙 -deck:1a.中文語彙::核二仟單字

Is it a current feature of the addon? 謝謝！

**Comment by ThoreBor** [comment]
Hi, great idea! 
I just added this feature to the add-on. It will be part of the next update. If you want to use it now, you can replace the `__init__.py, config.json and config.md` files in your add-on folder with the updated files from github.
